{"uuid":"275556a5-1c87-4b12-b07a-f0453f09a89f","name":"Scenario Outline: The user getting error message with invalid python code for Types of Linked List","children":["1929f9f4-c7cf-42cb-83f1-a1d3441aa03d"],"befores":[],"afters":[{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"My screenshot","source":"e3a97deb-67e2-4bca-894f-389790ca93d1-attachment","type":"image/png"},{"name":"Myscreenshot","source":"8bdcc203-d7c2-40fe-93a8-40d05e838ee8-attachment"}],"parameters":[],"start":1696885802916,"stop":1696885802964},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"AFTER_STEP is failed."},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696885802964,"stop":1696885802964},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"AFTER_STEP is failed."},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696885802965,"stop":1696885802965},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"AFTER_STEP is failed."},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696885802966,"stop":1696885802966}],"start":1696885802912,"stop":1696885802967}