{"uuid":"4d282fec-cc99-4efe-9b0a-f9fc2893cdd0","name":"Scenario Outline: The user getting error message with invalid python code for Types of Linked List","children":["b7290496-62ec-47c0-8def-e26ae296c671"],"befores":[],"afters":[{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"My screenshot","source":"2f4a1858-40f6-4a3e-8fde-6ac97862c090-attachment","type":"image/png"},{"name":"Myscreenshot","source":"dd0bbd6a-be85-4d1b-9cdf-4f260006aa0a-attachment"}],"parameters":[],"start":1696885864877,"stop":1696885865093},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"AFTER_STEP is failed."},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696885865094,"stop":1696885865094},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"AFTER_STEP is failed."},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696885865095,"stop":1696885865095},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"AFTER_STEP is failed."},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696885865095,"stop":1696885865095}],"start":1696885864874,"stop":1696885865096}