{"uuid":"53095045-da66-4869-a90a-11c593814fcc","name":"Scenario Outline: The user is presented with error message for invalid code in tryEditor for Max Consecutive Ones","children":["1f6dba92-fe5a-4453-bdfe-61fe2d9f180e"],"befores":[],"afters":[{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"My screenshot","source":"7e9475b9-578d-4129-8d61-66126e2a398c-attachment","type":"image/png"},{"name":"Myscreenshot","source":"072b8b76-4eea-48fc-bae4-deea953cc0a3-attachment"}],"parameters":[],"start":1696885799425,"stop":1696885799487},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"AFTER_STEP is failed."},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696885799487,"stop":1696885799488},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"AFTER_STEP is failed."},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696885799488,"stop":1696885799489},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"AFTER_STEP is failed."},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696885799489,"stop":1696885799489}],"start":1696885799406,"stop":1696885799490}