{"uuid":"8aa445c2-5e6e-4a88-a8a1-4451facbe6e5","name":"Scenario Outline: The user getting error message with invalid python code for Types of Linked List","children":["f64086ba-9d48-4bc1-9f77-585c86010fdc"],"befores":[],"afters":[{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696563740229,"stop":1696563740229},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696563740306,"stop":1696563740306},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696563740388,"stop":1696563740388},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696563742432,"stop":1696563742432}],"start":1696563739951,"stop":1696563742433}