{"uuid":"9c6e8f34-fb48-42bc-8693-344e2cc73706","name":"Scenario Outline: The user getting error message with invalid python code for Types of Linked List","children":["a1c74d3b-619a-4df1-85c8-47b41bd6b91b"],"befores":[],"afters":[{"name":"Hooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696390145578,"stop":1696390145578},{"name":"Hooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696390145749,"stop":1696390145749},{"name":"Hooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696390145798,"stop":1696390145798},{"name":"Hooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696390147838,"stop":1696390147839}],"start":1696390145398,"stop":1696390147840}