{"uuid":"a7562f0f-ef90-4968-ac19-0024ba853602","name":"Scenario Outline: The user getting error message with invalid python code for Types of Linked List","children":["a7009ca0-fcd8-4f6e-86d9-b5c3a289ea07"],"befores":[],"afters":[{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"My screenshot","source":"0ef070e8-7bc0-47c0-bcc0-0721b854f649-attachment","type":"image/png"},{"name":"Myscreenshot","source":"1525397d-6b45-48e0-943a-4c91a91d3269-attachment"}],"parameters":[],"start":1696885486754,"stop":1696885486796},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"AFTER_STEP is failed."},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696885486796,"stop":1696885486796},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"AFTER_STEP is failed."},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696885486797,"stop":1696885486797},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"AFTER_STEP is failed."},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696885486797,"stop":1696885486797}],"start":1696885486751,"stop":1696885486797}