{"uuid":"b566cee5-eb0a-46c3-9bba-467c51e1e4c5","name":"Scenario Outline: The user getting error message with invalid python code for Types of Linked List","children":["64dc6142-1a56-475f-9a12-b5bce91f423c"],"befores":[],"afters":[{"name":"Hooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696472207553,"stop":1696472207553},{"name":"Hooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696472207667,"stop":1696472207668},{"name":"Hooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696472207723,"stop":1696472207724},{"name":"Hooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696472209754,"stop":1696472209755}],"start":1696472207397,"stop":1696472209755}