{"uuid":"f0ee4c40-27f2-47e0-99d6-74a1d5f8d4e6","name":"Scenario Outline: The user is presented with error message for code with invalid syntax in tryEditor for Arrays in Python page","children":["49748f55-4ea5-47dd-8f56-dfd244de3744"],"befores":[],"afters":[{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"My screenshot","source":"1630d6a5-b6d3-4142-b75e-6f52e714341c-attachment","type":"image/png"},{"name":"Myscreenshot","source":"5b72971d-f7b2-4e68-bd85-f69e9eefc7e3-attachment"}],"parameters":[],"start":1696885481715,"stop":1696885481780},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"AFTER_STEP is failed."},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696885481781,"stop":1696885481781},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"AFTER_STEP is failed."},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696885481782,"stop":1696885481782},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"AFTER_STEP is failed."},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696885481783,"stop":1696885481783}],"start":1696885481694,"stop":1696885481784}